AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  crypto-tracker
  Literally tracking crypto prices from different sources because why not

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.9
    Handler: main.handler

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: raw-crypto-data
  TransformedDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: transformed-crypto-data
  HtmlExtractorFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/extract_html/
      Environment:
        Variables:
          RAW_DATA_BUCKET: !Ref RawDataBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref RawDataBucket
  CoinMarketcapTransformFn:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 8
      CodeUri: lambdas/transform_coinmarketcap/
      Environment:
        Variables:
          RAW_DATA_BUCKET: !Ref RawDataBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref RawDataBucket
  CsvLoaderFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/load_csv/
      Environment:
        Variables:
          TRANSFORMED_DATA_BUCKET: !Ref TransformedDataBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref TransformedDataBucket
  CoinMarketcapStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state_machines/coin_marketcap_etl.asl.json
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref HtmlExtractorFn
        - LambdaInvokePolicy:
            FunctionName: !Ref CoinMarketcapTransformFn
        - LambdaInvokePolicy:
            FunctionName: !Ref CsvLoaderFn
  CoinMarketcapMinerSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CoinMarketcapStateMachine-ExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt CoinMarketcapStateMachine.Arn
  CoinMarketcapMinerScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Run CoinMarketcap StateMachine every 5 minutes
      ScheduleExpression: rate(5 minutes)
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt CoinMarketcapStateMachine.Arn
        RoleArn: !GetAtt CoinMarketcapMinerSchedulerRole.Arn
