AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crypto-tracker
  Literally tracking crypto prices from different sources because why not

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.9
    Handler: main.handler
    

Resources:
  # HelloWorldFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: hello_world/
  #     Handler: app.lambda_handler
  #     Runtime: python3.9
  #     Architectures:
  #       - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           Path: /hello
  #           Method: get
  RawDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: raw-crypto-data
  TransformedDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: transformed-crypto-data
  HtmlExtractorFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/extract_html/
      Environment:
        Variables:
          RAW_DATA_BUCKET: !Ref RawDataBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref RawDataBucket
  CoinMarketcapTransformFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/transform_coinmarketcap/
      Environment:
        Variables:
          RAW_DATA_BUCKET: !Ref RawDataBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref RawDataBucket
  CsvLoaderFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/load_csv/
      Environment:
        Variables:
          TRANSFORMED_DATA_BUCKET: !Ref TransformedDataBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref TransformedDataBucket

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
